### ISSUE TITLE
There's no code

### ISSUE THREAD

**Issue by AndroidKitKat** [colfrog/jesi#1]
See title

**Comment by colfrog** [comment]
Hi, could you please go into convincing detail about why this is an issue and how this affects you as a user? You see, I was trained to believe that less code is better, so this is a confusing one to me.

I also can't think of an obvious fix right now, could you please propose an approach to fixing this issue for you?

Thank you for your support and involvement in this project.

**Comment by AndroidKitKat** [comment]
You added code so you're cool, dog.
